version: '3.9'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    ports:
      - 8080:8080       # Web UI
      - 6881:6881       # BitTorrent
      - 6881:6881/udp
    volumes:
      - ./config-qbittorrent:/config
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - WEBUI_PORT=8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:arm64v8-latest
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ./config-sonarr:/config
      - ./downloads:/downloads
      - ./tv:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - ./config-radarr:/config
      - ./downloads:/downloads
      - ./movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:arm64v8-latest
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ./config-jackett:/config
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config-homepage:/app/config
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    environment:
      - TZ=Africa/Nairobi
      - WEBPASSWORD=changeme
    volumes:
      - ./config-pihole/etc-pihole:/etc/pihole
      - ./config-pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

networks:
  default:
    name: media_network
