# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Home Network:
    - Pihole:
        icon: pi-hole
        href: http://192.168.100.13/admin
        description: Network Wide Ad-blocker
        widget:
          type: pihole
          url: http://192.168.100.13
          version: 6 # required if running v6 or higher, defaults to 5
          key: K6QKfRBV2HpH4AZpcjDP8yWoXy4sYIkAgjWTRB/puqQ=

    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.168.100.13:8080
        description: Torrent client
        widget:
          type: qbittorrent
          url: http://192.168.100.13:8080
          username: admin
          password: adminadmin

- Media:   
     - Jellyfin:
         icon: jellyfin
         href: http://192.168.100.13:8096/
         description: Movies/Shows/Music
         widget:
           type: jellyfin
           url: http://192.168.100.13:8096/
           key: 7a616ce4240b458fbf2854a9750ff17f

     - Sonarr:
         icon: sonarr
         href: http://192.168.100.13:8989 
         description: TV show downloader
         widget:
           type: sonarr
           url: http://192.168.100.13:8989
           key: 6102cdee48b2440d87fd0caaca655281

     - Radarr:
         icon: radarr
         href: http://192.168.100.13:7878
         description: Movie Downloader
         widget:
           type: radarr
           url: http://192.168.100.13
           key: 29397db203d64652aab9fc0f99b777a2

     - Jackett:
          icon: jackett
          href: http://192.168.100.13:9117
          description: Torrent indexer proxy
          container: jackett
          widget:

- Home Services:
    - Safaricom Fiber:
        icon: router
        href: https://192.168.100.1/
        description: Router
    - Docker:
        icon: docker
        href: https://containrrr.dev/watchtower/
        description: Auto-updates containers
        container: watchtower
